no_trace: false
debounce: 300
ignore: \.git/
trig: [run]

rules:
  - name: run
    match: \.(go|yaml)$
    ignore: _test\.go$
    command: go run cmd/graphql/graphql.go

  - name: test
    match: _test\.go$
    command: go test -cover {PKG}
