// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	// Author of message
	Author string `json:"author"`
	// Message content
	Message string `json:"message"`
}

type MessageInput struct {
	ClientMutationID string `json:"clientMutationID"`
	// Author's name
	Author string `json:"author"`
	// Message content
	Message string `json:"message"`
}
